# Site settings
title: LeeDC Blog
SEOTitle: 李东潮的博客 | LeeDC Blog
header-img: img/home-bg.jpg             # 1000*340 or 2000*680 is the best
email: lidongchao1992@gmail.com
description: "A blog belongs to Li Dongchao"
keyword: ""
url: "http://lidongchao.github.io"      # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
# weibo_username:     huxpro
# zhihu_username:     huxpro
github_username:    lidongchao
# twitter_username:  huxpro
# facebook_username:  huxpro



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10                            # num of post per page
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# plugins
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
# duoshuo_username: _your_duoshuo_short_name_
# Share component is depend on Comment so we can NOT use share only.
# duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
# ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
# ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
# ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "脚踏实地从零开始"
sidebar-avatar: /img/avatar-me.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "Hux Blog",
        href: "http://huangxuan.me"
    },{
        title: "火光摇曳",
        href: "http://www.flickering.cn"
    },{
        title: "WILDML",
        href: "http://www.wildml.com"
    },{
        title: "Chris Olah's blog",
        href: "http://colah.github.io"
    },{
        title: "寒小阳CSDN",
        href: "https://blog.csdn.net/han_xiaoyang/article/category/5877239"
    },{
        title: "刘建平Pinard",
        href: "http://www.cnblogs.com/pinard/"
    },{
        title: "zhbzz2007",
        href: "http://www.cnblogs.com/zhbzz2007"
    }
]
